### ISSUE TITLE
Web version

### ISSUE THREAD

**Issue by pabloscloud** [zood/george#81] opened 2023-04-30 18:33 UTC
I would love to share my location easily with my family, but they all use iPhones. I currently use Find my device but I guess sending my location via unencrypted sms isn't the best idea. Maybe you could add a web version where my family can login and see my location? Just a slimmed down version I guess

**Comment by arashpayan** [comment] 2023-05-02 15:34
I'm working on an iOS version of the app, so that'll solve the problem of sharing with folks on iPhones.

However, a 'read-only' web client that folks can log into on desktops is something I was going to add anyway because the Zood API provides for 'find my device' functionality. The necessary code is already implemented in the Android app, but there's no website that people can log into to activate it when they can't find their phone.

Dupe of https://github.com/zood/george/issues/31

**Closed by arashpayan** 2023-05-02 15:34 UTC

**Comment by pabloscloud** [comment] 2023-05-02 15:55
That's awesome and sorry for the duplicate. I searched using the keyword *web* and therefore didn't find it.

**Comment by arashpayan** [comment] 2023-05-02 16:01
No worries. :slightly_smiling_face:  The other issue doesn't make it immediately clear that a web client is required.
